#!/bin/bash

# ETH=192.168.1.??
# WIFI = 192.168.1.245

IP=192.168.1.245

pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/GUIClasses.py ./
pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/HeadlessClasses.py ./
pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/GUIMain.py ./
pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/HeadlessMain.py ./
pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/ProbeTest.py ./
pscp -pw dr0m3l scott@$IP:Programming/Python/IncubatorMonitor/UARTTest.py ./

