#!/bin/bash

UN=pi
#UN=scott

IP=192.168.1.53

pscp -pw dr0m3l ./GUIClasses.py $UN@$IP:Programming/Python/IncubatorMonitor/GUIClasses.py
pscp -pw dr0m3l ./HeadlessClasses.py $UN@$IP:Programming/Python/IncubatorMonitor/HeadlessClasses.py
pscp -pw dr0m3l ./GUIMain.py $UN@$IP:Programming/Python/IncubatorMonitor/GUIMain.py
pscp -pw dr0m3l ./HeadlessMain.py $UN@$IP:Programming/Python/IncubatorMonitor/HeadlessMain.py
pscp -pw dr0m3l ./ProbeTest.py $UN@$IP:Programming/Python/IncubatorMonitor/ProbeTest.py
pscp -pw dr0m3l ./UARTTest.py $UN@$IP:Programming/Python/IncubatorMonitor/UARTTest.p53